# Generated by Django 2.1.13 on 2019-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(blank=True, max_length=20, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=10, null=True)),
                ('facility_desc', models.CharField(blank=True, max_length=32, null=True)),
                ('facility_attr0', models.CharField(blank=True, max_length=20, null=True)),
                ('facility_attr27', models.CharField(blank=True, max_length=60, null=True)),
                ('facility_attr28', models.CharField(blank=True, max_length=80, null=True)),
                ('basin', models.CharField(blank=True, db_column='Basin', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Model2_Name',
            },
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointid', models.CharField(blank=True, db_column='PointId', max_length=8, null=True)),
                ('pointidlong', models.CharField(blank=True, db_column='PointIdLong', max_length=31, null=True)),
                ('facilityid', models.CharField(blank=True, db_column='FacilityID', max_length=20, null=True)),
                ('udc', models.CharField(blank=True, db_column='UDC', max_length=10, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=24, null=True)),
                ('longdescription', models.CharField(blank=True, db_column='LongDescription', max_length=80, null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=16, null=True)),
                ('units', models.CharField(blank=True, db_column='Units', max_length=8, null=True)),
            ],
            options={
                'db_table': 'Model3_Name',
            },
        ),
    ]
