# Generated by Django 2.1.5 on 2019-10-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model1',
            table='Model1_Name',
        ),
    ]
